---
title: "EC2 Spot Instance"
format: html
editor: visual
---

### Setup local environment

For passing commands between R and Bash environments

```{r sync-renv-bash}

library(jsonlite)
library(here)

cwd <- here::here()

Sys.setenv("CWD"=cwd)

```

```{bash}

aws ec2 describe-instances --output json --profile pgx --region us-east-2 | tee ${CWD}/ec2-config/ec2_description.json

```

```{bash}

aws ec2 describe-instances --query 'Reservations[*].Instances[*].InstanceId' --output json --profile pgx --region us-east-2 | tee ${CWD}/ec2-config/ec2_id.json


```

```{r parse-ec2-cluster-id}

ec2_id_json <- read_json(here("ec2-config","ec2_id.json"))

ec2_id <- as.data.frame(ec2_id_json[[1]][[1]])

names(ec2_id)  <- "ec2_id"

write.table(ec2_id, here("ec2-config","ec2_id.csv"), sep = ";", col.names = FALSE, row.names = FALSE)

ec2_id

# Save as environmental variable
Sys.setenv("EC2_ID"=ec2_id)

```

```{bash}

aws ec2 start-instances --instance-ids ${EC2_ID} --profile pgx --region us-east-2

```

#### Allocate Elastic IP to AWS EMR Head Node

```{sh allocate-elastic-ip}

aws ec2 associate-address --instance-id ${EC2_ID} --allocation-id eipalloc-06014a5131df97d79 --profile pgx --region us-east-2

```

```{bash}
pwd
```
